# Generated by Django 3.2.16 on 2022-12-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='your first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='your last name')),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('special_requirements', models.TextField()),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
