# Generated by Django 3.2.16 on 2022-12-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_group_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='group_size',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
